site_name: Web SDK
site_description: "WebSDK is a library for quickly and easily creating SDKs for integration with third-party APIs."
site_author: "Extralait"
site_url: ""
repo_name: extralait/web-sdk
repo_url: https://github.com/extralait/web-sdk
extra_css:
  - stylesheets/extra.css
edit_uri: edit/main/docs/
extra:
  version:
    provider: mike
theme:
  name: material
  language: en
  icon:
    annotation: material/plus-circle
  palette:
    - media: "(prefers-color-scheme)"
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-auto
        name: "Switch to light mode"
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-7
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-4
        name: "Switch to system preference"
  highlightjs: true
  hljs_languages:
    - yaml
    - python
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.prune
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.path
    #    - navigation.indexes
    - navigation.top
    - toc.follow
    - content.code.annotate
  logo: 'resources/logo.svg'
  favicon: 'resources/favicon.png'
nav:
  - Get Started:
      - Welcome: index.md
      - Installation: pages/get_started/installation.md
  - Backends:
      - Sync:
          - REST requests: pages/backends/rest/requests/index.md
          - SOAP requests: pages/backends/soap/requests/index.md
      - Async:
          - REST httpx: pages/backends/rest/httpx/index.md
          - SOAP httpx: pages/backends/soap/httpx/index.md
markdown_extensions:
  - abbr
  - footnotes
  - toc:
      permalink: true
  - tables
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - codehilite
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.snippets:
      base_path: docs/examples
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - autorefs
  - social
  - search
  - tags
  - mike:
      alias_type: symlink
      canonical_version: latest
  - llmstxt:
      enabled: !ENV [CI, false]
      full_output: llms-full.txt
      markdown_description: |-
        WebSDK is a library for quickly and easily creating SDKs
        for integration with third-party APIs, works since python version 3.10.
      sections:
        REST documentation:
          - rest/*.md
        SOAP documentation:
          - soap/*.md
        Contrib:
          - pydantic/*.md
        Utils:
          - utils/*md
  - exclude:
      glob:
        - plugins/*
        - __pycache__/*
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          import:
            - http://python-eve.org/objects.inv
          options:
            extensions:
              - griffe_inherited_docstrings
            find_stubs_package: true
            summary: true
            relative_crossrefs: true
            merge_init_into_class: true
            inherited_members: true
            allow_inspection: true
            annotations_path: source
            line_length: 60
            separate_signature: true
            signature_crossrefs: false
            modernize_annotations: true
            docstring_style: google
            docstring_section_style: spacy
            docstring_options:
              trim_doctest_flags: true
              warn_unknown_params: true
              ignore_init_summary: true
            show_docstring_attributes: false
            show_docstring_functions: true
            show_docstring_classes: true
            show_docstring_modules: true
            show_docstring_description: true
            show_docstring_examples: true
            show_docstring_other_parameters: true
            show_docstring_parameters: true
            show_docstring_raises: true
            show_docstring_receives: true
            show_docstring_returns: true
            show_docstring_warns: true
            show_docstring_yields: true
            show_root_heading: true
            show_root_toc_entry: true
            show_root_full_path: false
            show_root_members_full_path: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_source: true
            show_object_full_path: false
            show_signature: true
            show_signature_annotations: true
            show_category_heading: true
            show_if_no_docstring: true
            show_labels: true
            show_bases: true
            show_inheritance_diagram: true
            show_submodules: false
            heading_level: 2
            parameter_headings: true
            members_order: source
            group_by_category: true
            paths:
              - /agora
            preload_modules:
              - __future__
              - pydantic
              - datetime
              - abc
            filters:
              - "!^_"
              - "__"
              - "!^__slots__"
              - "!^__all__"
